### ISSUE TITLE
Set visual theme for first day presentation

### ISSUE THREAD

**Issue by sebastianbarry** [sebastianbarry/Senior-Design-Capstone#3]
We need to agree on a theme for the first day presentation (jun 9 2022)

**Comment by sebastianbarry** [comment]
I think the presentation should be PINK

**Comment by CyR1en** [comment]
> I think the presentation should be PINK

Hard agree

**Comment by kevinhawekotte** [comment]
Second that.

**Comment by sebastianbarry** [comment]
https://olucdenver-my.sharepoint.com/:p:/g/personal/kevin_hawekotte_ucdenver_edu/EThJnFzrUERCgduOpAxZgUcBoGOYm-sUAZAouz1zMg44ig?e=nTIehd

**Comment by sebastianbarry** [comment]
Team picked the presentation theme:

https://strawpoll.com/polls/61gDBe1Oayw

https://slidesgo.com/theme/coffee-shop-business-plan
